<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class StockMovementLineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the stock_movement_lines table with initial data.
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        try { DB::table('stock_movement_lines')->truncate(); } catch (\Exception $e) {}
        Schema::enableForeignKeyConstraints();

        DB::table('stock_movement_lines')->insert([
            [
                'id' => 1,
                'stock_movement_id' => 1,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => 120,
                'cost_price' => null,
                'created_at' => '2025-12-06 04:40:36',
                'updated_at' => '2025-12-06 04:40:36'
            ],
            [
                'id' => 2,
                'stock_movement_id' => 2,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => -40,
                'cost_price' => 3000,
                'created_at' => '2025-12-06 05:00:00',
                'updated_at' => '2025-12-06 05:00:00'
            ],
            [
                'id' => 3,
                'stock_movement_id' => 3,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -3,
                'cost_price' => 3000,
                'created_at' => '2025-12-06 05:05:13',
                'updated_at' => '2025-12-06 05:05:13'
            ],
            [
                'id' => 4,
                'stock_movement_id' => 4,
                'item_id' => 4,
                'item_name' => 'Aqua 600ml',
                'unit_id' => 3,
                'factor' => 24,
                'qty' => 96,
                'cost_price' => 50000,
                'created_at' => '2025-12-06 05:27:36',
                'updated_at' => '2025-12-06 05:27:36'
            ],
            [
                'id' => 5,
                'stock_movement_id' => 5,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => 120,
                'cost_price' => null,
                'created_at' => '2025-12-06 05:33:11',
                'updated_at' => '2025-12-06 05:33:11'
            ],
            [
                'id' => 6,
                'stock_movement_id' => 6,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -3,
                'cost_price' => 3000,
                'created_at' => '2025-12-06 05:42:05',
                'updated_at' => '2025-12-06 05:42:05'
            ],
            [
                'id' => 7,
                'stock_movement_id' => 6,
                'item_id' => 4,
                'item_name' => 'Aqua 600ml',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 2100,
                'created_at' => '2025-12-06 05:42:05',
                'updated_at' => '2025-12-06 05:42:05'
            ],
            [
                'id' => 8,
                'stock_movement_id' => 7,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-06 07:38:24',
                'updated_at' => '2025-12-06 07:38:24'
            ],
            [
                'id' => 9,
                'stock_movement_id' => 8,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => -40,
                'cost_price' => 3000,
                'created_at' => '2025-12-08 04:04:49',
                'updated_at' => '2025-12-08 04:04:49'
            ],
            [
                'id' => 10,
                'stock_movement_id' => 9,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-08 11:17:12',
                'updated_at' => '2025-12-08 11:17:12'
            ],
            [
                'id' => 11,
                'stock_movement_id' => 10,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 10:10:25',
                'updated_at' => '2025-12-10 10:10:25'
            ],
            [
                'id' => 12,
                'stock_movement_id' => 11,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => -40,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 10:14:32',
                'updated_at' => '2025-12-10 10:14:32'
            ],
            [
                'id' => 13,
                'stock_movement_id' => 12,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 10:17:00',
                'updated_at' => '2025-12-10 10:17:00'
            ],
            [
                'id' => 14,
                'stock_movement_id' => 13,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 10:18:54',
                'updated_at' => '2025-12-10 10:18:54'
            ],
            [
                'id' => 15,
                'stock_movement_id' => 14,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 10:29:10',
                'updated_at' => '2025-12-10 10:29:10'
            ],
            [
                'id' => 16,
                'stock_movement_id' => 15,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:18:28',
                'updated_at' => '2025-12-10 11:18:28'
            ],
            [
                'id' => 17,
                'stock_movement_id' => 16,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:19:09',
                'updated_at' => '2025-12-10 11:19:09'
            ],
            [
                'id' => 18,
                'stock_movement_id' => 17,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:19:31',
                'updated_at' => '2025-12-10 11:19:31'
            ],
            [
                'id' => 19,
                'stock_movement_id' => 18,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:21:00',
                'updated_at' => '2025-12-10 11:21:00'
            ],
            [
                'id' => 20,
                'stock_movement_id' => 19,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:22:16',
                'updated_at' => '2025-12-10 11:22:16'
            ],
            [
                'id' => 21,
                'stock_movement_id' => 20,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:22:33',
                'updated_at' => '2025-12-10 11:22:33'
            ],
            [
                'id' => 22,
                'stock_movement_id' => 21,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:24:37',
                'updated_at' => '2025-12-10 11:24:37'
            ],
            [
                'id' => 23,
                'stock_movement_id' => 22,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:30:15',
                'updated_at' => '2025-12-10 11:30:15'
            ],
            [
                'id' => 24,
                'stock_movement_id' => 23,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:35:20',
                'updated_at' => '2025-12-10 11:35:20'
            ],
            [
                'id' => 25,
                'stock_movement_id' => 24,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:38:19',
                'updated_at' => '2025-12-10 11:38:19'
            ],
            [
                'id' => 26,
                'stock_movement_id' => 25,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:42:22',
                'updated_at' => '2025-12-10 11:42:22'
            ],
            [
                'id' => 27,
                'stock_movement_id' => 26,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:44:06',
                'updated_at' => '2025-12-10 11:44:06'
            ],
            [
                'id' => 28,
                'stock_movement_id' => 27,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:45:35',
                'updated_at' => '2025-12-10 11:45:35'
            ],
            [
                'id' => 29,
                'stock_movement_id' => 28,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:49:01',
                'updated_at' => '2025-12-10 11:49:01'
            ],
            [
                'id' => 30,
                'stock_movement_id' => 29,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:53:03',
                'updated_at' => '2025-12-10 11:53:03'
            ],
            [
                'id' => 31,
                'stock_movement_id' => 30,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:53:36',
                'updated_at' => '2025-12-10 11:53:36'
            ],
            [
                'id' => 32,
                'stock_movement_id' => 31,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:54:13',
                'updated_at' => '2025-12-10 11:54:13'
            ],
            [
                'id' => 33,
                'stock_movement_id' => 32,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:54:38',
                'updated_at' => '2025-12-10 11:54:38'
            ],
            [
                'id' => 34,
                'stock_movement_id' => 33,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 11:56:48',
                'updated_at' => '2025-12-10 11:56:48'
            ],
            [
                'id' => 35,
                'stock_movement_id' => 34,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:02:24',
                'updated_at' => '2025-12-10 12:02:24'
            ],
            [
                'id' => 36,
                'stock_movement_id' => 35,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:04:54',
                'updated_at' => '2025-12-10 12:04:54'
            ],
            [
                'id' => 37,
                'stock_movement_id' => 36,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:08:08',
                'updated_at' => '2025-12-10 12:08:08'
            ],
            [
                'id' => 38,
                'stock_movement_id' => 37,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:11:25',
                'updated_at' => '2025-12-10 12:11:25'
            ],
            [
                'id' => 39,
                'stock_movement_id' => 38,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:13:03',
                'updated_at' => '2025-12-10 12:13:03'
            ],
            [
                'id' => 40,
                'stock_movement_id' => 39,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:16:44',
                'updated_at' => '2025-12-10 12:16:44'
            ],
            [
                'id' => 41,
                'stock_movement_id' => 40,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:19:16',
                'updated_at' => '2025-12-10 12:19:16'
            ],
            [
                'id' => 42,
                'stock_movement_id' => 41,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:28:38',
                'updated_at' => '2025-12-10 12:28:38'
            ],
            [
                'id' => 43,
                'stock_movement_id' => 42,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:30:56',
                'updated_at' => '2025-12-10 12:30:56'
            ],
            [
                'id' => 44,
                'stock_movement_id' => 43,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:31:36',
                'updated_at' => '2025-12-10 12:31:36'
            ],
            [
                'id' => 45,
                'stock_movement_id' => 44,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:33:57',
                'updated_at' => '2025-12-10 12:33:57'
            ],
            [
                'id' => 46,
                'stock_movement_id' => 45,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:36:09',
                'updated_at' => '2025-12-10 12:36:09'
            ],
            [
                'id' => 47,
                'stock_movement_id' => 46,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:42:53',
                'updated_at' => '2025-12-10 12:42:53'
            ],
            [
                'id' => 48,
                'stock_movement_id' => 47,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:43:22',
                'updated_at' => '2025-12-10 12:43:22'
            ],
            [
                'id' => 49,
                'stock_movement_id' => 48,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:46:51',
                'updated_at' => '2025-12-10 12:46:51'
            ],
            [
                'id' => 50,
                'stock_movement_id' => 49,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 12:51:03',
                'updated_at' => '2025-12-10 12:51:03'
            ],
            [
                'id' => 51,
                'stock_movement_id' => 50,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-10 13:17:35',
                'updated_at' => '2025-12-10 13:17:35'
            ],
            [
                'id' => 52,
                'stock_movement_id' => 51,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => 120,
                'cost_price' => null,
                'created_at' => '2025-12-11 12:52:15',
                'updated_at' => '2025-12-11 12:52:15'
            ],
            [
                'id' => 53,
                'stock_movement_id' => 52,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-12 14:51:51',
                'updated_at' => '2025-12-12 14:51:51'
            ],
            [
                'id' => 54,
                'stock_movement_id' => 53,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-12 14:51:52',
                'updated_at' => '2025-12-12 14:51:52'
            ],
            [
                'id' => 55,
                'stock_movement_id' => 54,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-12 14:53:04',
                'updated_at' => '2025-12-12 14:53:04'
            ],
            [
                'id' => 56,
                'stock_movement_id' => 55,
                'item_id' => 3,
                'item_name' => 'Mie Sedaap Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => 120,
                'cost_price' => null,
                'created_at' => '2025-12-15 14:09:18',
                'updated_at' => '2025-12-15 14:09:18'
            ],
            [
                'id' => 57,
                'stock_movement_id' => 56,
                'item_id' => 3,
                'item_name' => 'Mie Sedaap Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => -80,
                'cost_price' => 3000,
                'created_at' => '2025-12-15 14:09:53',
                'updated_at' => '2025-12-15 14:09:53'
            ],
            [
                'id' => 58,
                'stock_movement_id' => 57,
                'item_id' => 5,
                'item_name' => 'Aqua 1500ml',
                'unit_id' => 3,
                'factor' => 12,
                'qty' => 48,
                'cost_price' => null,
                'created_at' => '2025-12-15 14:20:02',
                'updated_at' => '2025-12-15 14:20:02'
            ],
            [
                'id' => 59,
                'stock_movement_id' => 58,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => -40,
                'cost_price' => 3000,
                'created_at' => '2025-12-15 14:21:31',
                'updated_at' => '2025-12-15 14:21:31'
            ],
            [
                'id' => 60,
                'stock_movement_id' => 58,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2025-12-15 14:21:31',
                'updated_at' => '2025-12-15 14:21:31'
            ],
            [
                'id' => 61,
                'stock_movement_id' => 58,
                'item_id' => 5,
                'item_name' => 'Aqua 1500ml',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 4500,
                'created_at' => '2025-12-15 14:21:31',
                'updated_at' => '2025-12-15 14:21:31'
            ],
            [
                'id' => 62,
                'stock_movement_id' => 58,
                'item_id' => 4,
                'item_name' => 'Aqua 600ml',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 2100,
                'created_at' => '2025-12-15 14:21:31',
                'updated_at' => '2025-12-15 14:21:31'
            ],
            [
                'id' => 63,
                'stock_movement_id' => 59,
                'item_id' => 4,
                'item_name' => 'Aqua 600ml',
                'unit_id' => 3,
                'factor' => 24,
                'qty' => 48,
                'cost_price' => null,
                'created_at' => '2025-12-17 12:36:19',
                'updated_at' => '2025-12-17 12:36:19'
            ],
            [
                'id' => 64,
                'stock_movement_id' => 60,
                'item_id' => 3,
                'item_name' => 'Mie Sedaap Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => 120,
                'cost_price' => null,
                'created_at' => '2025-12-17 12:36:43',
                'updated_at' => '2025-12-17 12:36:43'
            ],
            [
                'id' => 65,
                'stock_movement_id' => 61,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-03 13:45:44',
                'updated_at' => '2026-01-03 13:45:44'
            ],
            [
                'id' => 66,
                'stock_movement_id' => 62,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => -40,
                'cost_price' => 3000,
                'created_at' => '2026-01-26 14:37:40',
                'updated_at' => '2026-01-26 14:37:40'
            ],
            [
                'id' => 67,
                'stock_movement_id' => 62,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 2,
                'factor' => 5,
                'qty' => -5,
                'cost_price' => 3000,
                'created_at' => '2026-01-26 14:37:40',
                'updated_at' => '2026-01-26 14:37:40'
            ],
            [
                'id' => 68,
                'stock_movement_id' => 62,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-26 14:37:40',
                'updated_at' => '2026-01-26 14:37:40'
            ],
            [
                'id' => 69,
                'stock_movement_id' => 62,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-26 14:37:40',
                'updated_at' => '2026-01-26 14:37:40'
            ],
            [
                'id' => 70,
                'stock_movement_id' => 63,
                'item_id' => 4,
                'item_name' => 'Aqua 600ml',
                'unit_id' => 3,
                'factor' => 24,
                'qty' => 72,
                'cost_price' => null,
                'created_at' => '2026-01-27 02:29:14',
                'updated_at' => '2026-01-27 02:29:14'
            ],
            [
                'id' => 71,
                'stock_movement_id' => 64,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -29,
                'cost_price' => 3000,
                'created_at' => '2026-01-27 02:30:54',
                'updated_at' => '2026-01-27 02:30:54'
            ],
            [
                'id' => 72,
                'stock_movement_id' => 64,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-27 02:30:54',
                'updated_at' => '2026-01-27 02:30:54'
            ],
            [
                'id' => 73,
                'stock_movement_id' => 64,
                'item_id' => 3,
                'item_name' => 'Mie Sedaap Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-27 02:30:54',
                'updated_at' => '2026-01-27 02:30:54'
            ],
            [
                'id' => 74,
                'stock_movement_id' => 65,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => 200,
                'cost_price' => null,
                'created_at' => '2026-01-27 02:49:41',
                'updated_at' => '2026-01-27 02:49:41'
            ],
            [
                'id' => 75,
                'stock_movement_id' => 66,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 3,
                'factor' => 40,
                'qty' => -40,
                'cost_price' => 10000,
                'created_at' => '2026-01-27 02:52:56',
                'updated_at' => '2026-01-27 02:52:56'
            ],
            [
                'id' => 76,
                'stock_movement_id' => 67,
                'item_id' => 6,
                'item_name' => 'Indomie Goreng 1',
                'unit_id' => 3,
                'factor' => 24,
                'qty' => 48,
                'cost_price' => null,
                'created_at' => '2026-01-27 03:04:37',
                'updated_at' => '2026-01-27 03:04:37'
            ],
            [
                'id' => 77,
                'stock_movement_id' => 68,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 10000,
                'created_at' => '2026-01-27 03:07:05',
                'updated_at' => '2026-01-27 03:07:05'
            ],
            [
                'id' => 78,
                'stock_movement_id' => 69,
                'item_id' => 6,
                'item_name' => 'Indomie Goreng 1',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-29 14:23:29',
                'updated_at' => '2026-01-29 14:23:29'
            ],
            [
                'id' => 79,
                'stock_movement_id' => 70,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-30 05:45:06',
                'updated_at' => '2026-01-30 05:45:06'
            ],
            [
                'id' => 80,
                'stock_movement_id' => 70,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-30 05:45:06',
                'updated_at' => '2026-01-30 05:45:06'
            ],
            [
                'id' => 81,
                'stock_movement_id' => 70,
                'item_id' => 3,
                'item_name' => 'Mie Sedaap Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 3000,
                'created_at' => '2026-01-30 05:45:06',
                'updated_at' => '2026-01-30 05:45:06'
            ],
            [
                'id' => 82,
                'stock_movement_id' => 70,
                'item_id' => 4,
                'item_name' => 'Aqua 600ml',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -1,
                'cost_price' => 2100,
                'created_at' => '2026-01-30 05:45:06',
                'updated_at' => '2026-01-30 05:45:06'
            ],
            [
                'id' => 83,
                'stock_movement_id' => 71,
                'item_id' => 3,
                'item_name' => 'Mie Sedaap Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -2,
                'cost_price' => 3000,
                'created_at' => '2026-01-30 05:45:24',
                'updated_at' => '2026-01-30 05:45:24'
            ],
            [
                'id' => 84,
                'stock_movement_id' => 71,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -4,
                'cost_price' => 3000,
                'created_at' => '2026-01-30 05:45:24',
                'updated_at' => '2026-01-30 05:45:24'
            ],
            [
                'id' => 85,
                'stock_movement_id' => 71,
                'item_id' => 2,
                'item_name' => 'Indomie Ayam Bawang',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -4,
                'cost_price' => 3000,
                'created_at' => '2026-01-30 05:45:24',
                'updated_at' => '2026-01-30 05:45:24'
            ],
            [
                'id' => 86,
                'stock_movement_id' => 72,
                'item_id' => 1,
                'item_name' => 'Indomie Goreng',
                'unit_id' => 1,
                'factor' => 1,
                'qty' => -8,
                'cost_price' => 3000,
                'created_at' => '2026-02-04 01:28:35',
                'updated_at' => '2026-02-04 01:28:35'
            ]
        ]);
    }
}